const cards = [
  { word: "Apfel", category: "Essen", search: "Apfel Frucht" },
  { word: "Banane", category: "Essen", search: "Banane Frucht" },
  { word: "Brot", category: "Essen", search: "Brot Lebensmittel" },
  { word: "Tomate", category: "Essen", search: "Tomate Gemüse" },
  { word: "Kartoffel", category: "Essen", search: "Kartoffel Gemüse" },
  { word: "Käse", category: "Essen", search: "Käse Lebensmittel" },
  { word: "Tasse", category: "Alltag", search: "Tasse Trinkgefäß" },
  { word: "Stuhl", category: "Alltag", search: "Stuhl Möbel" },
  { word: "Haus", category: "Alltag", search: "Wohnhaus Gebäude" },
  { word: "Schlüssel", category: "Alltag", search: "Türschlüssel" },
  { word: "Tisch", category: "Alltag", search: "Tisch Möbel" },
  { word: "Lampe", category: "Alltag", search: "Lampe Leuchte" },
  { word: "Fahrrad", category: "Freizeit", search: "Fahrrad Zweirad" },
  { word: "Ball", category: "Freizeit", search: "Spielball" },
  { word: "Buch", category: "Freizeit", search: "Buch lesen" },
  { word: "Garten", category: "Freizeit", search: "Garten Grünanlage" },
  { word: "Kamera", category: "Freizeit", search: "Fotokamera" },
  { word: "Puzzle", category: "Freizeit", search: "Puzzle Spiel" },
  { word: "Hund", category: "Tiere", search: "Haushund" },
  { word: "Katze", category: "Tiere", search: "Hauskatze" },
  { word: "Pferd", category: "Tiere", search: "Pferd Tier" },
  { word: "Vogel", category: "Tiere", search: "Vogel Tier" },
  { word: "Fisch", category: "Tiere", search: "Fisch Tier" },
  { word: "Kaninchen", category: "Tiere", search: "Kaninchen Tier" },
  { word: "Baum", category: "Natur", search: "Baum Natur" },
  { word: "Blume", category: "Natur", search: "Blume Pflanze" },
  { word: "Sonne", category: "Natur", search: "Sonne Himmel" },
  { word: "Wolke", category: "Natur", search: "Wolke Himmel" },
  { word: "Regen", category: "Natur", search: "Regen Wetter" },
  { word: "Meer", category: "Natur", search: "Meer Landschaft" },
  { word: "Auto", category: "Verkehr", search: "PKW Auto" },
  { word: "Bus", category: "Verkehr", search: "Omnibus Fahrzeug" },
  { word: "Zug", category: "Verkehr", search: "Eisenbahnzug" },
  { word: "Ampel", category: "Verkehr", search: "Verkehrsampel" },
  { word: "Straße", category: "Verkehr", search: "Straße Verkehr" },
  { word: "Bahnhof", category: "Verkehr", search: "Bahnhof Gebäude" },
  { word: "Arzt", category: "Gesundheit", search: "Arzt Medizin" },
  { word: "Krankenhaus", category: "Gesundheit", search: "Krankenhaus Gebäude" },
  { word: "Tablette", category: "Gesundheit", search: "Tablette Medikament" },
  { word: "Verband", category: "Gesundheit", search: "Wundverband" },
  { word: "Rollstuhl", category: "Gesundheit", search: "Rollstuhl" },
  { word: "Therapie", category: "Gesundheit", search: "Therapie Behandlung" },
  { word: "Mutter", category: "Menschen", search: "Mutter Familie" },
  { word: "Vater", category: "Menschen", search: "Vater Familie" },
  { word: "Kind", category: "Menschen", search: "Kind Person" },
  { word: "Freund", category: "Menschen", search: "Freunde Menschen" },
  { word: "Frau", category: "Menschen", search: "Frau Person" },
  { word: "Mann", category: "Menschen", search: "Mann Person" },
  { word: "Schule", category: "Orte", search: "Schule Gebäude" },
  { word: "Supermarkt", category: "Orte", search: "Supermarkt" },
  { word: "Park", category: "Orte", search: "Stadtpark" },
  { word: "Kirche", category: "Orte", search: "Kirche Gebäude" },
  { word: "Bäckerei", category: "Orte", search: "Bäckerei Geschäft" },
  { word: "Apotheke", category: "Orte", search: "Apotheke Geschäft" },
  { word: "Laufen", category: "Verben", search: "Mensch läuft" },
  { word: "Schlafen", category: "Verben", search: "Mensch schläft" },
  { word: "Trinken", category: "Verben", search: "Mensch trinkt" },
  { word: "Essen", category: "Verben", search: "Mensch isst" },
  { word: "Lesen", category: "Verben", search: "Mensch liest" },
  { word: "Schreiben", category: "Verben", search: "Mensch schreibt" },
  { word: "Fröhlich", category: "Gefühle", search: "fröhlicher Mensch" },
  { word: "Traurig", category: "Gefühle", search: "trauriger Mensch" },
  { word: "Müde", category: "Gefühle", search: "müder Mensch" },
  { word: "Ängstlich", category: "Gefühle", search: "ängstlicher Mensch" },
  { word: "Wütend", category: "Gefühle", search: "wütender Mensch" },
  { word: "Ruhig", category: "Gefühle", search: "ruhiger Mensch" }
];
