const cards = [
  { word: "Sonne", category: "Natur", emoji: "☀️", syllables: "Son-ne", example: "Die Sonne scheint." },
  { word: "Mond", category: "Natur", emoji: "🌙", syllables: "Mond", example: "Der Mond steht am Himmel." },
  { word: "Baum", category: "Natur", emoji: "🌳", syllables: "Baum", example: "Der Baum hat grüne Blätter." },
  { word: "Blume", category: "Natur", emoji: "🌸", syllables: "Blu-me", example: "Die Blume blüht." },
  { word: "Regen", category: "Natur", emoji: "🌧️", syllables: "Re-gen", example: "Der Regen fällt vom Himmel." },
  { word: "Schnee", category: "Natur", emoji: "❄️", syllables: "Schnee", example: "Der Schnee ist weiß." },
  { word: "Hund", category: "Tiere", emoji: "🐶", syllables: "Hund", example: "Der Hund läuft im Garten." },
  { word: "Katze", category: "Tiere", emoji: "🐱", syllables: "Kat-ze", example: "Die Katze schläft." },
  { word: "Vogel", category: "Tiere", emoji: "🐦", syllables: "Vo-gel", example: "Der Vogel fliegt." },
  { word: "Pferd", category: "Tiere", emoji: "🐴", syllables: "Pferd", example: "Das Pferd steht auf der Wiese." },
  { word: "Fisch", category: "Tiere", emoji: "🐟", syllables: "Fisch", example: "Der Fisch schwimmt." },
  { word: "Apfel", category: "Essen", emoji: "🍎", syllables: "Ap-fel", example: "Ich esse einen Apfel." },
  { word: "Banane", category: "Essen", emoji: "🍌", syllables: "Ba-na-ne", example: "Die Banane ist gelb." },
  { word: "Brot", category: "Essen", emoji: "🍞", syllables: "Brot", example: "Ich schneide das Brot." },
  { word: "Käse", category: "Essen", emoji: "🧀", syllables: "Kä-se", example: "Der Käse liegt auf dem Brot." },
  { word: "Tomate", category: "Essen", emoji: "🍅", syllables: "To-ma-te", example: "Die Tomate ist rot." },
  { word: "Haus", category: "Alltag", emoji: "🏠", syllables: "Haus", example: "Das Haus hat ein Dach." },
  { word: "Tür", category: "Alltag", emoji: "🚪", syllables: "Tür", example: "Ich öffne die Tür." },
  { word: "Fenster", category: "Alltag", emoji: "🪟", syllables: "Fens-ter", example: "Das Fenster ist offen." },
  { word: "Stuhl", category: "Alltag", emoji: "🪑", syllables: "Stuhl", example: "Ich sitze auf dem Stuhl." },
  { word: "Bett", category: "Alltag", emoji: "🛏️", syllables: "Bett", example: "Ich schlafe im Bett." },
  { word: "Lampe", category: "Alltag", emoji: "💡", syllables: "Lam-pe", example: "Die Lampe leuchtet." },
  { word: "Auto", category: "Verkehr", emoji: "🚗", syllables: "Au-to", example: "Ich fahre mit dem Auto." },
  { word: "Fahrrad", category: "Verkehr", emoji: "🚲", syllables: "Fahr-rad", example: "Ich fahre mit dem Fahrrad." },
  { word: "Bus", category: "Verkehr", emoji: "🚌", syllables: "Bus", example: "Der Bus hält an." },
  { word: "Zug", category: "Verkehr", emoji: "🚆", syllables: "Zug", example: "Der Zug fährt zum Bahnhof." },
  { word: "Ampel", category: "Verkehr", emoji: "🚦", syllables: "Am-pel", example: "Die Ampel zeigt Grün." },
  { word: "Arzt", category: "Gesundheit", emoji: "👨‍⚕️", syllables: "Arzt", example: "Der Arzt untersucht mich." },
  { word: "Ärztin", category: "Gesundheit", emoji: "👩‍⚕️", syllables: "Ärz-tin", example: "Die Ärztin spricht mit mir." },
  { word: "Krankenhaus", category: "Gesundheit", emoji: "🏥", syllables: "Kran-ken-haus", example: "Das Krankenhaus ist groß." },
  { word: "Tablette", category: "Gesundheit", emoji: "💊", syllables: "Ta-blet-te", example: "Ich nehme eine Tablette." },
  { word: "Verband", category: "Gesundheit", emoji: "🩹", syllables: "Ver-band", example: "Der Verband schützt die Wunde." },
  { word: "Mann", category: "Menschen", emoji: "👨", syllables: "Mann", example: "Der Mann trägt eine Jacke." },
  { word: "Frau", category: "Menschen", emoji: "👩", syllables: "Frau", example: "Die Frau lächelt." },
  { word: "Kind", category: "Menschen", emoji: "🧒", syllables: "Kind", example: "Das Kind spielt." },
  { word: "Mutter", category: "Menschen", emoji: "👩‍👧", syllables: "Mut-ter", example: "Die Mutter hilft." },
  { word: "Vater", category: "Menschen", emoji: "👨‍👦", syllables: "Va-ter", example: "Der Vater liest." },
  { word: "Fröhlich", category: "Gefühle", emoji: "😊", syllables: "Fröh-lich", example: "Ich bin fröhlich." },
  { word: "Traurig", category: "Gefühle", emoji: "😢", syllables: "Trau-rig", example: "Die Person ist traurig." },
  { word: "Müde", category: "Gefühle", emoji: "😴", syllables: "Mü-de", example: "Ich bin müde." },
  { word: "Wütend", category: "Gefühle", emoji: "😡", syllables: "Wü-tend", example: "Der Mann ist wütend." },
  { word: "Ängstlich", category: "Gefühle", emoji: "😨", syllables: "Ängst-lich", example: "Das Kind ist ängstlich." },
  { word: "Laufen", category: "Verben", emoji: "🏃", syllables: "Lau-fen", example: "Ich laufe durch den Park." },
  { word: "Schlafen", category: "Verben", emoji: "🛌", syllables: "Schla-fen", example: "Ich schlafe im Bett." },
  { word: "Lesen", category: "Verben", emoji: "📖", syllables: "Le-sen", example: "Ich lese ein Buch." },
  { word: "Schreiben", category: "Verben", emoji: "✍️", syllables: "Schrei-ben", example: "Ich schreibe einen Satz." },
  { word: "Trinken", category: "Verben", emoji: "🥤", syllables: "Trin-ken", example: "Ich trinke Wasser." },
  { word: "Sprechen", category: "Verben", emoji: "🗣️", syllables: "Spre-chen", example: "Ich spreche langsam." }
];
