const cards = [
  { word: "Apfel", category: "Essen", symbol: "🍎", syllables: "Ap-fel", example: "Ich esse einen Apfel." },
  { word: "Banane", category: "Essen", symbol: "🍌", syllables: "Ba-na-ne", example: "Die Banane ist gelb." },
  { word: "Brot", category: "Essen", symbol: "🍞", syllables: "Brot", example: "Ich schneide das Brot." },
  { word: "Käse", category: "Essen", symbol: "🧀", syllables: "Kä-se", example: "Der Käse liegt auf dem Brot." },
  { word: "Kartoffel", category: "Essen", symbol: "🥔", syllables: "Kar-tof-fel", example: "Die Kartoffel liegt auf dem Teller." },
  { word: "Tomate", category: "Essen", symbol: "🍅", syllables: "To-ma-te", example: "Die Tomate ist rot." },
  { word: "Milch", category: "Essen", symbol: "🥛", syllables: "Milch", example: "Ich trinke Milch." },
  { word: "Wasser", category: "Essen", symbol: "💧", syllables: "Was-ser", example: "Ich trinke Wasser." },
  { word: "Kaffee", category: "Essen", symbol: "☕", syllables: "Kaf-fee", example: "Ich trinke Kaffee." },
  { word: "Ei", category: "Essen", symbol: "🥚", syllables: "Ei", example: "Das Ei liegt im Eierbecher." },
  { word: "Hund", category: "Tiere", symbol: "🐶", syllables: "Hund", example: "Der Hund läuft im Garten." },
  { word: "Katze", category: "Tiere", symbol: "🐱", syllables: "Kat-ze", example: "Die Katze schläft." },
  { word: "Pferd", category: "Tiere", symbol: "🐴", syllables: "Pferd", example: "Das Pferd steht auf der Wiese." },
  { word: "Vogel", category: "Tiere", symbol: "🐦", syllables: "Vo-gel", example: "Der Vogel fliegt." },
  { word: "Fisch", category: "Tiere", symbol: "🐟", syllables: "Fisch", example: "Der Fisch schwimmt." },
  { word: "Kaninchen", category: "Tiere", symbol: "🐰", syllables: "Ka-nin-chen", example: "Das Kaninchen frisst." },
  { word: "Kuh", category: "Tiere", symbol: "🐄", syllables: "Kuh", example: "Die Kuh steht auf der Weide." },
  { word: "Schwein", category: "Tiere", symbol: "🐷", syllables: "Schwein", example: "Das Schwein lebt auf dem Bauernhof." },
  { word: "Biene", category: "Tiere", symbol: "🐝", syllables: "Bie-ne", example: "Die Biene fliegt zur Blume." },
  { word: "Schmetterling", category: "Tiere", symbol: "🦋", syllables: "Schmet-ter-ling", example: "Der Schmetterling ist bunt." },
  { word: "Haus", category: "Alltag", symbol: "🏠", syllables: "Haus", example: "Das Haus hat ein Dach." },
  { word: "Tür", category: "Alltag", symbol: "🚪", syllables: "Tür", example: "Ich öffne die Tür." },
  { word: "Fenster", category: "Alltag", symbol: "🪟", syllables: "Fens-ter", example: "Das Fenster ist offen." },
  { word: "Stuhl", category: "Alltag", symbol: "🪑", syllables: "Stuhl", example: "Ich sitze auf dem Stuhl." },
  { word: "Tisch", category: "Alltag", symbol: "🛋️", syllables: "Tisch", example: "Das Essen steht auf dem Tisch." },
  { word: "Bett", category: "Alltag", symbol: "🛏️", syllables: "Bett", example: "Ich schlafe im Bett." },
  { word: "Lampe", category: "Alltag", symbol: "💡", syllables: "Lam-pe", example: "Die Lampe leuchtet." },
  { word: "Schlüssel", category: "Alltag", symbol: "🔑", syllables: "Schlüs-sel", example: "Ich öffne die Tür mit dem Schlüssel." },
  { word: "Telefon", category: "Alltag", symbol: "📱", syllables: "Te-le-fon", example: "Ich telefoniere." },
  { word: "Uhr", category: "Alltag", symbol: "🕒", syllables: "Uhr", example: "Die Uhr zeigt drei Uhr." },
  { word: "Auto", category: "Verkehr", symbol: "🚗", syllables: "Au-to", example: "Ich fahre mit dem Auto." },
  { word: "Fahrrad", category: "Verkehr", symbol: "🚲", syllables: "Fahr-rad", example: "Ich fahre mit dem Fahrrad." },
  { word: "Bus", category: "Verkehr", symbol: "🚌", syllables: "Bus", example: "Der Bus hält an." },
  { word: "Zug", category: "Verkehr", symbol: "🚆", syllables: "Zug", example: "Der Zug fährt zum Bahnhof." },
  { word: "Ampel", category: "Verkehr", symbol: "🚦", syllables: "Am-pel", example: "Die Ampel zeigt Grün." },
  { word: "Straße", category: "Verkehr", symbol: "🛣️", syllables: "Stra-ße", example: "Das Auto fährt auf der Straße." },
  { word: "Bahnhof", category: "Verkehr", symbol: "🚉", syllables: "Bahn-hof", example: "Ich warte am Bahnhof." },
  { word: "Flugzeug", category: "Verkehr", symbol: "✈️", syllables: "Flug-zeug", example: "Das Flugzeug fliegt." },
  { word: "Schiff", category: "Verkehr", symbol: "🚢", syllables: "Schiff", example: "Das Schiff fährt über das Meer." },
  { word: "Rollstuhl", category: "Verkehr", symbol: "🦽", syllables: "Roll-stuhl", example: "Der Rollstuhl steht im Flur." },
  { word: "Sonne", category: "Natur", symbol: "☀️", syllables: "Son-ne", example: "Die Sonne scheint." },
  { word: "Mond", category: "Natur", symbol: "🌙", syllables: "Mond", example: "Der Mond steht am Himmel." },
  { word: "Baum", category: "Natur", symbol: "🌳", syllables: "Baum", example: "Der Baum hat grüne Blätter." },
  { word: "Blume", category: "Natur", symbol: "🌸", syllables: "Blu-me", example: "Die Blume blüht." },
  { word: "Regen", category: "Natur", symbol: "🌧️", syllables: "Re-gen", example: "Der Regen fällt." },
  { word: "Schnee", category: "Natur", symbol: "❄️", syllables: "Schnee", example: "Der Schnee ist weiß." },
  { word: "Wolke", category: "Natur", symbol: "☁️", syllables: "Wol-ke", example: "Die Wolke zieht über den Himmel." },
  { word: "Meer", category: "Natur", symbol: "🌊", syllables: "Meer", example: "Das Meer ist blau." },
  { word: "Wald", category: "Natur", symbol: "🌲", syllables: "Wald", example: "Im Wald stehen viele Bäume." },
  { word: "Berg", category: "Natur", symbol: "⛰️", syllables: "Berg", example: "Der Berg ist hoch." },
  { word: "Arzt", category: "Gesundheit", symbol: "👨‍⚕️", syllables: "Arzt", example: "Der Arzt untersucht mich." },
  { word: "Ärztin", category: "Gesundheit", symbol: "👩‍⚕️", syllables: "Ärz-tin", example: "Die Ärztin spricht mit mir." },
  { word: "Krankenhaus", category: "Gesundheit", symbol: "🏥", syllables: "Kran-ken-haus", example: "Das Krankenhaus ist groß." },
  { word: "Tablette", category: "Gesundheit", symbol: "💊", syllables: "Ta-blet-te", example: "Ich nehme eine Tablette." },
  { word: "Verband", category: "Gesundheit", symbol: "🩹", syllables: "Ver-band", example: "Der Verband schützt die Wunde." },
  { word: "Herz", category: "Gesundheit", symbol: "❤️", syllables: "Herz", example: "Mein Herz schlägt." },
  { word: "Hand", category: "Gesundheit", symbol: "✋", syllables: "Hand", example: "Ich hebe meine Hand." },
  { word: "Fuß", category: "Gesundheit", symbol: "🦶", syllables: "Fuß", example: "Mein Fuß steht auf dem Boden." },
  { word: "Therapie", category: "Gesundheit", symbol: "🧠", syllables: "The-ra-pie", example: "Die Therapie hilft mir." },
  { word: "Blutdruck", category: "Gesundheit", symbol: "🩺", syllables: "Blut-druck", example: "Ich messe meinen Blutdruck." },
  { word: "Mann", category: "Menschen", symbol: "👨", syllables: "Mann", example: "Der Mann trägt eine Jacke." },
  { word: "Frau", category: "Menschen", symbol: "👩", syllables: "Frau", example: "Die Frau lächelt." },
  { word: "Kind", category: "Menschen", symbol: "🧒", syllables: "Kind", example: "Das Kind spielt." },
  { word: "Mutter", category: "Menschen", symbol: "👩‍👧", syllables: "Mut-ter", example: "Die Mutter hilft." },
  { word: "Vater", category: "Menschen", symbol: "👨‍👦", syllables: "Va-ter", example: "Der Vater liest." },
  { word: "Freund", category: "Menschen", symbol: "🧑‍🤝‍🧑", syllables: "Freund", example: "Mein Freund besucht mich." },
  { word: "Lehrer", category: "Menschen", symbol: "👨‍🏫", syllables: "Leh-rer", example: "Der Lehrer erklärt die Aufgabe." },
  { word: "Bäcker", category: "Menschen", symbol: "👨‍🍳", syllables: "Bä-cker", example: "Der Bäcker backt Brot." },
  { word: "Polizei", category: "Menschen", symbol: "👮", syllables: "Po-li-zei", example: "Die Polizei regelt den Verkehr." },
  { word: "Familie", category: "Menschen", symbol: "👨‍👩‍👧‍👦", syllables: "Fa-mi-lie", example: "Meine Familie sitzt am Tisch." },
  { word: "Fröhlich", category: "Gefühle", symbol: "😊", syllables: "Fröh-lich", example: "Ich bin fröhlich." },
  { word: "Traurig", category: "Gefühle", symbol: "😢", syllables: "Trau-rig", example: "Die Person ist traurig." },
  { word: "Müde", category: "Gefühle", symbol: "😴", syllables: "Mü-de", example: "Ich bin müde." },
  { word: "Wütend", category: "Gefühle", symbol: "😡", syllables: "Wü-tend", example: "Der Mann ist wütend." },
  { word: "Ängstlich", category: "Gefühle", symbol: "😨", syllables: "Ängst-lich", example: "Das Kind ist ängstlich." },
  { word: "Ruhig", category: "Gefühle", symbol: "😌", syllables: "Ru-hig", example: "Ich sitze ruhig." },
  { word: "Überrascht", category: "Gefühle", symbol: "😮", syllables: "Ü-ber-rascht", example: "Die Frau ist überrascht." },
  { word: "Lachen", category: "Gefühle", symbol: "😂", syllables: "La-chen", example: "Wir lachen zusammen." },
  { word: "Weinen", category: "Gefühle", symbol: "😭", syllables: "Wei-nen", example: "Das Kind muss weinen." },
  { word: "Liebe", category: "Gefühle", symbol: "🥰", syllables: "Lie-be", example: "Liebe ist ein schönes Gefühl." },
  { word: "Laufen", category: "Verben", symbol: "🏃", syllables: "Lau-fen", example: "Ich laufe durch den Park." },
  { word: "Schlafen", category: "Verben", symbol: "🛌", syllables: "Schla-fen", example: "Ich schlafe im Bett." },
  { word: "Lesen", category: "Verben", symbol: "📖", syllables: "Le-sen", example: "Ich lese ein Buch." },
  { word: "Schreiben", category: "Verben", symbol: "✍️", syllables: "Schrei-ben", example: "Ich schreibe einen Satz." },
  { word: "Trinken", category: "Verben", symbol: "🥤", syllables: "Trin-ken", example: "Ich trinke Wasser." },
  { word: "Essen", category: "Verben", symbol: "🍽️", syllables: "Es-sen", example: "Wir essen gemeinsam." },
  { word: "Sprechen", category: "Verben", symbol: "🗣️", syllables: "Spre-chen", example: "Ich spreche langsam." },
  { word: "Hören", category: "Verben", symbol: "👂", syllables: "Hö-ren", example: "Ich höre Musik." },
  { word: "Sehen", category: "Verben", symbol: "👀", syllables: "Se-hen", example: "Ich sehe einen Vogel." },
  { word: "Fahren", category: "Verben", symbol: "🚴", syllables: "Fah-ren", example: "Ich fahre mit dem Fahrrad." },
  { word: "Schule", category: "Orte", symbol: "🏫", syllables: "Schu-le", example: "Die Kinder gehen zur Schule." },
  { word: "Supermarkt", category: "Orte", symbol: "🛒", syllables: "Su-per-markt", example: "Ich kaufe im Supermarkt ein." },
  { word: "Apotheke", category: "Orte", symbol: "⚕️", syllables: "A-po-the-ke", example: "Ich hole Medikamente in der Apotheke." },
  { word: "Bäckerei", category: "Orte", symbol: "🥐", syllables: "Bä-cke-rei", example: "Ich kaufe Brot in der Bäckerei." },
  { word: "Park", category: "Orte", symbol: "🏞️", syllables: "Park", example: "Ich gehe im Park spazieren." },
  { word: "Kirche", category: "Orte", symbol: "⛪", syllables: "Kir-che", example: "Die Kirche steht im Dorf." },
  { word: "Restaurant", category: "Orte", symbol: "🍴", syllables: "Res-tau-rant", example: "Wir essen im Restaurant." },
  { word: "Hotel", category: "Orte", symbol: "🏨", syllables: "Ho-tel", example: "Ich schlafe im Hotel." },
  { word: "Strand", category: "Orte", symbol: "🏖️", syllables: "Strand", example: "Ich gehe am Strand spazieren." },
  { word: "Garten", category: "Orte", symbol: "🌻", syllables: "Gar-ten", example: "Im Garten wachsen Blumen." }
];
