const ARTICLES=new Set(["der","die","das","den","dem","des","ein","eine","einen","einem","einer"]);
const VERBS={"kauf":"kauft","kaufe":"kauft","lauf":"läuft","laufe":"läuft","fahr":"fährt","fahre":"fährt","geh":"geht","gehe":"geht","komm":"kommt","komme":"kommt","mach":"macht","mache":"macht","spiel":"spielt","spiele":"spielt","trink":"trinkt","trinke":"trinkt","ess":"isst","esse":"isst","seh":"sieht","sehe":"sieht","les":"liest","lese":"liest","schreib":"schreibt","schreibe":"schreibt","sprech":"spricht","spreche":"spricht","schlaf":"schläft","schlafe":"schläft","sitz":"sitzt","sitze":"sitzt","steh":"steht","stehe":"steht","lach":"lacht","lache":"lacht","koch":"kocht","koche":"kocht","arbeit":"arbeitet","arbeite":"arbeitet","wart":"wartet","warte":"wartet","lern":"lernt","lerne":"lernt","sing":"singt","singe":"singt","tanz":"tanzt","tanze":"tanzt"};
const COMMON=new Set(["ist","sind","war","waren","hat","haben",...Object.values(VERBS)]);
function norm(v){return String(v||"").toLocaleLowerCase("de-DE").replace(/[.,!?;:()\"]/g," ").replace(/\s+/g," ").trim()}
function cap(v){return v?v.charAt(0).toLocaleUpperCase("de-DE")+v.slice(1):""}
function finish(v){const s=String(v||"").trim(),r=cap(s);return !r?"":/[.!?]$/.test(r)?r:r+"."}
function hasTarget(s,t){const w=norm(s).split(" "),x=norm(t),r=x.slice(0,Math.max(4,x.length-2));return w.some(a=>a===x||a.startsWith(r)||(x.startsWith(a)&&a.length>=4))}
function hasVerb(s){return norm(s).split(" ").some(w=>COMMON.has(VERBS[w]||w))}
function getExamples(c){return Array.isArray(c.examples)&&c.examples.length?c.examples:[c.example,c.example2].filter(Boolean)}
function getExample(c){const e=getExamples(c);return e[Math.floor(Math.random()*e.length)]||""}
function improveSentence(s,c){let w=norm(s).split(" ").filter(Boolean);if(!w.length)return getExample(c);const t=norm(c.word);if(w[0]===t&&c.article)w.unshift(norm(c.article));w=w.map(x=>VERBS[x]||x);w=w.map((x,i)=>(x===t||ARTICLES.has(w[i-1]))?cap(x):x);w[0]=cap(w[0]);return finish(w.join(" "))}
function rules(d){return d==="leicht"?{min:2,label:"kurzen Satz"}:d==="schwer"?{min:6,label:"längeren Satz"}:{min:4,label:"vollständigen Satz"}}
function evaluateSentence(c,s,d="mittel"){const q=norm(s),r=rules(d);if(!q)return{status:"🎤 Noch kein Satz",message:"Sprich oder schreibe zuerst einen Satz.",suggestion:getExample(c),level:"empty",checks:{target:false,verb:false,length:false,understood:false}};const n=q.split(" ").length,target=hasTarget(q,c.word),verb=hasVerb(q),length=n>=r.min,understood=target&&(verb||n>=2);let status="🔁 Noch einmal versuchen",message=`Versuche einen ${r.label} mit dem Wort „${c.word}“.`,level="retry";if(target&&verb&&length){status="⭐⭐⭐ Sehr gut!";message="Ich habe deinen Satz verstanden.";level="good"}else if(target&&(verb||length)){status="⭐⭐ Gut erkannt!";message="Das Zielwort ist enthalten. Der Satz ist gut verständlich.";level="almost"}else if(target){status="⭐ Guter Anfang!";message="Ergänze noch ein Verb oder weitere Wörter.";level="start"}return{status,message,suggestion:target?improveSentence(s,c):getExample(c),level,checks:{target,verb,length,understood}}}
function buildSentenceBlocks(c){const b=new Set();getExamples(c).forEach(e=>{const w=String(e||"").replace(/[.!?]/g,"").split(/\s+/).filter(Boolean);if(w.length>=2)b.add(w.slice(0,2).join(" "));if(w.length>=3)b.add(w.slice(2).join(" "))});if(c.article&&c.word)b.add(`${c.article} ${c.word}`);return [...b].slice(0,6)}